# frontend/Dockerfile

# Stage 1: Build the React app
FROM node:16-alpine as builder
WORKDIR /app
COPY ../package.json .
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the app with a lightweight server
FROM nginx:1.21-alpine
COPY --from=builder /app/build /usr/share/nginx/html
# Copy the nginx config file
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]  